//
//  Constants.h
//  ConnectSDK
//
//  Created by Jeff Day on 5/4/16.
//  Copyright © 2016 Connected Interactive. All rights reserved.
//

#ifndef Constants_h
#define Constants_h

#define CONNECTTRACKER_SDK_VERSION @"1159"
#define CONNECTTRACKER_URL_SCHEME @"https"
#define CONNECTTRACKER_HOSTNAME @"ads.connectedinteractive.com" //
#define CONNECTTRACKER_BASE_URL CONNECTTRACKER_URL_SCHEME @"://" CONNECTTRACKER_HOSTNAME
#define CONNECTTRACKER_REACHABILITY_URL CONNECTTRACKER_URL_SCHEME @"://" @"ads.connectedinteractive.com"
#define CONNECTTRACKER_LOCATION_URL CONNECTTRACKER_BASE_URL @"/api/track_location/" CONNECTTRACKER_SDK_VERSION @"/"
#define CONNECTTRACKER_INIT_URL CONNECTTRACKER_BASE_URL @"/api/init_ios" CONNECTTRACKER_SDK_VERSION
#define CONNECTTRACKER_APNS_REGISTER_URL CONNECTTRACKER_BASE_URL @"/api/apns_register" CONNECTTRACKER_SDK_VERSION @"/"
#define CONNECTTRACKER_IMPRESSION_TRACKER_URL CONNECTTRACKER_BASE_URL @"/api/impression_l/"
#define CONNECTTRACKER_DELETE_DEVICE_DATA_URL CONNECTTRACKER_BASE_URL @"/api/delete_device_data/ios"
#define CONNECTTRACKER_CUSTOM_URI_SCHEME @"connectsdk"
#define CONNECTTRACKER_LOGGING_FILENAME @"ConnectedEventLog"
#define CONNECTTRACKER_IMPRESSIONIDUSERDEFAULT @"CONNECTIMPRESSIONID"

#endif /* Constants_h */
