version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2
  macos-orb: circleci/macos@2.4.1
jobs:
  test-ios:
    macos:
      xcode: 15.2.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.16.9
      - macos-orb/preboot-simulator:
          device: iPhone 15
          version: "17.2"
      - run:
          name: Test
          command: cd example && flutter pub get && flutter test integration_test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  test-android:
    environment:
      FL_OUTPUT_DIR: output
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.16.9
      - run:
          name: Create avd
          command: |
            SYSTEM_IMAGES="system-images;android-29;default;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
      - run:
          name: Launch emulator
          command: |
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true
      - run:
          name: Generate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed
      - run:
          name: Wait for emulator to start
          command: |
            circle-android wait-for-boot
      - run:
          name: Disable emulator animations
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
      - run:
          name: Run INTEGRATION tests
          command: cd example && flutter pub get && flutter test integration_test
      - restore_cache:
          key: gradle-v1-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  release_new_version:
    macos:
      xcode: 15.2.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.16.9
      - run:
          name: Pub Get
          command: flutter pub get 
      - run:
          name: Activate cider
          command: |
            export PATH="$PATH":"$HOME/.pub-cache/bin"
            pub global activate cider
      - run:
          name: Bump Version and update change log
          command: |
            echo "$LAST_COMMIT=$(git log -1 --pretty=%B | cat)" >> "$BASH_ENV"
            echo "$BUMP_TYPE=$(echo $LAST_COMMIT| cut -d'_' -f 2)
            cider bump $BUMP_TYPE
workflows:
  flutter_sdk_test_workflow:
    jobs:
      - test-ios
      - test-android
      - release_new_version